@startuml
skinparam linetype ortho
skinparam component {
    BorderColor #000000
}
title Clean architecture Attempt

rectangle "Business Rules" {
[tennis-use-case] as uc #ff6666
[tennis-domain] as domain #ffff99
}

rectangle "Frameworks & Drivers" {
[tennis-console-app] as consoleApp #99ccff
[tennis-rest-spring-app] as restSpringApp #99ccff
[tennis-rest-quarkus-app] as restQuarkusApp #99ccff
}

rectangle "Adapters" {
[tennis-controller] as controller #ccffcc
[tennis-player-gateway-in-memory] as player_gateway #ccffcc
[tennis-mapper-mapstruct] as mapper #ccffcc
}

consoleApp -D-> controller
restQuarkusApp  -D-> controller
restSpringApp -D-> controller

controller -D-> uc

uc -D-> domain
mapper -R-|> uc
mapper -R-> domain

player_gateway  -R-|> uc

@enduml