AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS TennisApiGatewayAwsLamdaMicronautApp API - tennis.api.gateway.aws.lamda.micronaut.app::tennis-api-gateway-aws-lamda-micronaut-app
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  TennisApiGatewayAwsLamdaMicronautAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tennis.api.gateway.aws.lamda.micronaut.app.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/exploded
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  TennisApiGatewayAwsLamdaMicronautAppApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: TennisApiGatewayAwsLamdaMicronautAppApi
